[build]
	command = "npm run build"
	publish = "build"
	functions = "functions"

[dev]
	functions = "functions"

# redirects to clean up our api urls
# [[redirects]]
# 	from = "/api/*" # the path we want to redirect
# 	to = "/.netlify/functions/api/:splat" # the url or path we want to redirect to
# 	status = 200

# redirects for react router
[[redirects]]
	from = "/*" # redirect all routes
	to = "/index.html" # to the index.html file that contains all the react app code
	status = 200