# [build]
# 	base = "client"
# 	command = "yarn build"
# 	functions = "functions"
# 	node_bundler = "esbuild"
# 	publish = "client/build"

# [dev]
# 	base = "client"
# 	command = "npm run start"
# 	functions = "functions"
# 	node_bundler = "esbuild"
# 	publish = "client"