[build]
	command = "npm run build"
	publish = "build"
	functions = "server/functions"

[dev]
	functions = "server/functions"

# redirects to clean up our api routes
[[redirects]]
	from = "https://gosurf-app.netlify.app/api/*" # the path we want to redirect
	to = "https://gosurf-app.netlify.app/.netlify/functions/api/:splat" # the url or path we want to mimick
	status = 200

# redirects for react router
[[redirects]]
	from = "/*" # redirect all routes
	to = "/index.html" # to the index.html file that contains all the react app code
	status = 200
